name: thermunet
channels:
  - pytorch
  - defaults
dependencies:
  - _tflow_select=2.1.0
  - absl-py=0.8.1
  - astor=0.8.0
  - attrs=19.1.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - ca-certificates=2019.8.28
  - certifi=2019.9.11
  - cffi=1.12.2
  - cloudpickle=1.2.2
  - colorama=0.4.1
  - cudatoolkit=10.0.130
  - cudnn=7.6.0
  - cycler=0.10.0
  - cytoolz=0.10.0
  - dask-core=2.5.0
  - decorator=4.3.2
  - defusedxml=0.5.0
  - entrypoints=0.3
  - freetype=2.9.1
  - gast=0.3.2
  - h5py=2.9.0
  - hdf5=1.10.4
  - icc_rt=2019.0.0
  - icu=58.2
  - imageio=2.5.0
  - intel-openmp=2019.1
  - ipykernel=5.1.0
  - ipython=7.3.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jedi=0.13.3
  - jinja2=2.10.3
  - joblib=0.13.2
  - jpeg=9b
  - jsonschema=3.0.1
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - kiwisolver=1.1.0
  - libpng=1.6.37
  - libprotobuf=3.9.2
  - libsodium=1.0.16
  - libtiff=4.0.10
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.1.1
  - markupsafe=1.1.1
  - matplotlib=3.1.0
  - mistune=0.8.4
  - mkl=2019.4
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - msys2-conda-epoch=20160418
  - nbconvert=5.4.1
  - nbformat=4.4.0
  - networkx=2.3
  - ninja=1.8.2
  - notebook=5.7.6
  - numpy=1.16.2
  - numpy-base=1.16.2
  - olefile=0.46
  - openssl=1.1.1d
  - pandas=0.25.1
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.3.4
  - pickleshare=0.7.5
  - pillow=5.4.1
  - pip=19.0.3
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - pycparser=2.19
  - pygments=2.3.1
  - pyparsing=2.4.0
  - pyqt=5.9.2
  - pyreadline=2.1
  - pyrsistent=0.14.11
  - python=3.6.8
  - python-dateutil=2.8.0
  - pytorch=1.0.1
  - pytz=2019.1
  - pywavelets=1.0.3
  - pywinpty=0.5.5
  - pyzmq=18.0.0
  - qt=5.9.7
  - qtconsole=4.4.3
  - scikit-image=0.15.0
  - scikit-learn=0.21.1
  - scipy=1.2.1
  - send2trash=1.5.0
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.27.2
  - tensorflow=1.14.0
  - tensorflow-base=1.14.0
  - tensorflow-estimator=1.14.0
  - tensorflow-gpu=1.14.0
  - termcolor=1.1.0
  - terminado=0.8.1
  - testpath=0.4.2
  - tk=8.6.8
  - toolz=0.10.0
  - torchvision=0.2.2
  - tornado=6.0.1
  - traitlets=4.3.2
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.16.0
  - wheel=0.33.1
  - widgetsnbextension=3.4.2
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.11.2
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - click==7.0
    - flask==1.1.1
    - grpcio==1.24.1
    - itsdangerous==1.1.0
    - protobuf==3.10.0
    - ptflops==0.4
    - setuptools==41.4.0
    - tensorboard==2.0.0
    - tensorboardx==1.9
    - torchsummary==1.5.1
    - visualdl==1.3.0


